[tool.poetry]
name = "pythonproject"
version = "0.1.0"
description = "hometask_poetry"
authors = ["Terenteva Viktoria <verba4182@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[tool.poetry.group.lint.dependencies]
black = "^24.4.2"
isort = "^5.13.2"
mypy = "^1.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
